on:
  workflow_call:
jobs:
  call-api:
    runs-on: self-hosted
    steps:
      - name: Call API
        run: |
          response=$(curl -sS https://jsonplaceholder.typicode.com/posts/1)
          echo "API Response:"
          echo "$response"
